config/routes.rb
Rails.application.routes.draw do
  resources :memories
  root 'memories#new'

end

app/models/memory.rb
class Memory < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only: [:show, :edit, :update, :destroy]

  # GET /memories
  # GET /memories.json
  def index
    @memories = Memory.all
  end

  # GET /memories/1
  # GET /memories/1.json
  def show
  end

  # GET /memories/new
  def new
    @memory = Memory.new
  end

  # GET /memories/1/edit
  def edit
  end

  # POST /memories
  # POST /memories.json
  def create
    @memory = Memory.new(memory_params)

    respond_to do |format|
      if @memory.save
        format.html { redirect_to root_path + "#contact", notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @memory }
      else
        format.html { render :new }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memories/1
  # PATCH/PUT /memories/1.json
  def update
    respond_to do |format|
      if @memory.update(memory_params)
        format.html { redirect_to @memory, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @memory }
      else
        format.html { render :edit }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memories/1
  # DELETE /memories/1.json
  def destroy
    @memory.destroy
    respond_to do |format|
      format.html { redirect_to memories_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory
      @memory = Memory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memory_params
      params.require(:memory).permit(:name, :email, :relationship, :year_met, :memory1, :memory2, :memory3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Lordy, Lordy, Courtney is 40</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= google_fonts_link_tag 'Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic|Montserrat:700|Merriweather:400italic|Belgrano' %>  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-custom">
	<%= yield %>
</body>
</html>

app/views/memories/_form.html.erb
<div id="contact-form">
  <%= form_for(@memory) do |f| %>
    <% if @memory.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@memory.errors.count, "error") %> prohibited this memory from being saved:</h2>

        <ul>
        <% @memory.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name %>
             <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-question-sign"></span></span>
                <%= f.text_field :name, placeholder: "Enter name", required: "required", class: "form-control", id: "name" %>
            </div>
          </div>
          <div class="form-group">
              <%= f.label :email %>
              <div class="input-group">
                  <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                  </span>
                  <%= f.email_field :email, class: "form-control", id: "email", placeholder: "Enter email", required: "required" %>
              </div>
          </div> 
          <div class="form-group">
            <%= f.label :relationship, "Relationship" %>
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon glyphicon-heart-empty"></span></span>
              <%= f.text_field :relationship, class: "form-control", placeholder: "Enter relationship" %>
              </div>
          </div>
          <div class="form-group">
            <%= f.label :year_met, "Year met" %>
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                </span>
                <%= f.text_field :year_met, class: "form-control", placeholder: "Enter year" %>
            </div>
          </div>
      </div>
      <div class="col-md-6">
          <div class="form-group">
            <%= f.label :memory1, "Message" %>
            <%= f.text_area :memory1, id: "message", class: "form-control", rows: "12", cols: "25", required: "required", placeholder: "Courtney, you are the greatest and here's why..." %>
          </div>
      </div>
      <div class="col-md-12">
            <%= f.submit 'Sign the Card', class: 'btn btn-skin pull-right', id: "btnContactUs" %>
      </div>
    </div>       
  <% end %>  
</div>

app/views/memories/edit.html.erb
<h1>Editing Memory</h1>

<%= render 'form' %>

<%= link_to 'Show', @memory %> |
<%= link_to 'Back', memories_path %>

app/views/memories/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<%#= link_to 'Share a Memory', new_memory_path, class: 'btn btn-primary' %>
<div id="bday-bg">
    <div class="container">
       <h1>Happy Birthday, Courtney!</h1>
        <p class="top">Click on your stack of birthday cards to read them.</p>
        <section class="main">

            <div class="baraja-demo">
                <ul id="baraja-el" class="baraja-container">
                    <% @memories.each do |memory| %>
                        <li><img src='<%= image_path(memory.name.downcase.gsub(/\s+/, "") + ".jpg") %>'>
                            <h4><%= memory.name %> 
                            <em style='font-size:.7em;text-transform:none'><%= memory.relationship.downcase %> 
                            <%= !memory.year_met.empty? ? 'since '+ memory.year_met : '' %>
                            </em></h4>
                            <p><%= memory.memory1 %></p>
                        </li>
                    <% end %>
                </ul>
            </div>
        </section>

        <nav class="actions light">
            <span id="nav-prev"><i class="fa fa fa-arrow-left"></i></span>
            <span id="nav-next"><i class="fa fa fa-arrow-right"></i></span>
            <!--<span id="close">close</span>-->
        </nav>
    </div>
</div>
<%= javascript_include_tag 'jquery.baraja', 'data-turbolinks-track' => true %>
<script type="text/javascript">    
        $( document ).ready(function() {
                var $el = $( '#baraja-el' );
                var baraja = $el.baraja();

                // navigation
                $( '#nav-prev' ).on( 'click', function( event ) {

                    baraja.previous();
                
                } );

                $( '#nav-next' ).on( 'click', function( event ) {

                    baraja.next();
                
                } );

                // simple fan
                $( '#nav-fan' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 90,
                        direction : 'right',
                        origin : { x : 25, y : 100 },
                        center : true
                    } );
                
                } );

                $( '#nav-fan2' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 90,
                        direction : 'left',
                        // note that the x origin changes (symmetric)
                        origin : { x : 75, y : 100 },
                        center : true
                    } );
                
                } );

                // more realistic fan: without common origin (means the origin changes / increments by card )
                $( '#nav-fan3' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 90,
                        direction : 'right',
                        origin : { minX : 20, maxX : 80, y : 100 },
                        center : true,
                        translation : 60
                    } );
                
                } );

                $( '#nav-fan4' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 90,
                        direction : 'left',
                        origin : { minX : 20, maxX : 80, y : 100 },
                        center : true,
                        translation : 60
                    } );
                
                } );

                // playing with different origins and ranges    
                $( '#nav-fan5' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 100,
                        direction : 'right',
                        origin : { x : 50, y : 200 },
                        center : true
                    } );
                
                } );

                $( '#nav-fan6' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 80,
                        direction : 'left',
                        origin : { x : 200, y : 50 },
                        center : true
                    } );
                
                } );

                // center false, playing with translation
                $( '#nav-fan7' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 20,
                        direction : 'right',
                        origin : { x : 50, y : 200 },
                        center : false,
                        translation : 300
                    } );
                
                } );

                $( '#nav-fan8' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 20,
                        direction : 'left',
                        origin : { x : 50, y : 200 },
                        center : false,
                        translation : 300
                    } );
                
                } );

                // using scatter : true
                $( '#nav-fan9' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 20,
                        direction : 'right',
                        origin : { x : 50, y : 200 },
                        center : false,
                        translation : 300,
                        scatter : true
                    } );
                
                } );

                $( '#nav-fan10' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 20,
                        direction : 'left',
                        origin : { x : 50, y : 200 },
                        center : false,
                        translation : 300,
                        scatter : true
                    } );
                
                } );

                $( '#nav-fanOther1' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 130,
                        direction : 'left',
                        origin : { x : 25, y : 100 },
                        center : false
                    } );
                
                } );

                $( '#nav-fanOther2' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 360,
                        direction : 'left',
                        origin : { x : 50, y : 90 },
                        center : false
                    } );
                
                } );

                $( '#nav-fanOther3' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 330,
                        direction : 'left',
                        origin : { x : 50, y : 100 },
                        center : true
                    } );
                
                } );

                $( '#nav-fanOther4' ).on( 'click', function( event ) {

                    baraja.fan( {
                        speed : 500,
                        easing : 'ease-out',
                        range : 90,
                        direction : 'right',
                        origin : { minX : 20, maxX : 80, y : 100 },
                        center : true,
                        translation : 60,
                        scatter : true
                    } );
                
                } );

                // close the baraja
                $( '#close' ).on( 'click', function( event ) {

                    baraja.close();
                
                } );

                // example of how to add more items
                $( '#add' ).on( 'click', function( event ) {

                    if( $( this ).hasClass( 'disabled' ) ) {
                        return false;
                    }

                    $( this ).addClass( 'disabled' );

                    baraja.add( $('<li><img src="images/6.jpg" alt="image6"/><h4>Serenity</h4><p>Truffaut wes anderson hoodie 3 wolf moon labore, fugiat lomo iphone eiusmod vegan.</p></li><li><img src="images/7.jpg" alt="image7"/><h4>Dark Honor</h4><p>Chillwave mustache pinterest, marfa seitan umami id farm-to-table iphone.</p></li><li><img src="images/8.jpg" alt="image8"/><h4>Nested Happiness</h4><p>Minim post-ironic banksy american apparel iphone wayfarers.</p></li><li><img src="images/9.jpg" alt="image9"/><h4>Cherry Country</h4><p>Sint vinyl Austin street art odd future id trust fund, terry richardson cray.</p></li>') );
                
                } );

            });
        </script>
        

app/views/memories/new.html.erb
	 <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <%= link_to(root_path, class: 'navbar-brand') do %>
				  <h1>Lordy, Lordy</h1>
				<% end %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
		      <ul class="nav navbar-nav">
		        <li class="active"><a href="#intro">Home</a></li>
		        <li><a href="#about">About</a></li>
				<li><a href="#service">Hobbies</a></li>
				<li><a href="#contact">Sign the Card</a></li>
		      </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav><!-- Section: intro -->
    <section id="intro" class="intro">
	
		<div class="slogan">
			<h2>Courtney turns</h2>
			<h3 class="number">40</h3>
			<h4>Scroll down for a <br/>super secret birthday card.</h4>
		</div>
		<div class="page-scroll">
			<a href="#contact" class="btn btn-circle">
				<i class="fa fa-angle-double-down animated"></i>
			</a>
		</div>
    </section>
	<!-- /Section: intro --> 

	<!-- Section: about -->
    <section id="about" class="home-section text-center">
		<div class="heading-about">
			<div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="wow bounceInDown" data-wow-delay="0.4s">
					<div class="section-heading">
					<h2>About Courtney</h2>
					<i class="fa fa-2x fa-angle-down"></i>

					</div>
					</div>
				</div>
			</div>
			</div>
		</div>
		<div class="container">

		<div class="row">
			<div class="col-lg-2 col-lg-offset-5">
				<hr class="marginbot-50">
			</div>
		</div>
        <div class="row">
            <div class="col-xs-6 col-sm-3 col-md-3">
				<div class="wow bounceInUp" data-wow-delay="0.2s">
                <div class="team boxed-grey">
                    <div class="inner">
						<h5>Day of Birth</h5>
                        <p class="subtitle">Jan 6, 1976</p>
                        <div class="avatar"><img src='<%= image_path "cr-parachute.jpg" %>' alt="" class="img-responsive img-circle" /></div>
                    </div>
                </div>
				</div>
            </div>
			<div class="col-xs-6 col-sm-3 col-md-3">
				<div class="wow bounceInUp" data-wow-delay="0.5s">
                <div class="team boxed-grey">
                    <div class="inner">
						<h5>Place of Birth</h5>
                        <p class="subtitle">Louisville, KY</p>
                        <div class="avatar"><img src='<%= image_path "cr-walkman.jpg" %>' class="img-responsive img-circle"></div>

                    </div>
                </div>
				</div>
            </div>
			<div class="col-xs-6 col-sm-3 col-md-3">
				<div class="wow bounceInUp" data-wow-delay="0.8s">
                <div class="team boxed-grey">
                    <div class="inner">
						<h5>Family</h5>
                        <p class="subtitle">The Knopfs</p>
                        <div class="avatar"><img src='<%= image_path "knopfs2.jpg" %>' alt="" class="img-responsive img-circle" /></div>

                    </div>
                </div>
				</div>
            </div>
			<div class="col-xs-6 col-sm-3 col-md-3">
				<div class="wow bounceInUp" data-wow-delay="1s">
                <div class="team boxed-grey">
                    <div class="inner">
						<h5>Partners in Crime</h5>
                        <p class="subtitle">Jaime, Frankie and CC</p>
                        <div class="avatar"><img src='<%= image_path "partners.jpg" %>' alt="" class="img-responsive img-circle" /></div>

                    </div>
                </div>
				</div>
            </div>
        </div>		
		</div>
	</section>
	<!-- /Section: about -->
	

	<!-- Section: services -->
    <section id="service" class="home-section text-center bg-gray">
		
		<div class="heading-about">
			<div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="wow bounceInDown" data-wow-delay="0.4s">
					<div class="section-heading">
					<h2>Hobbies</h2>
					<i class="fa fa-2x fa-angle-down"></i>

					</div>
					</div>
				</div>
			</div>
			</div>
		</div>
		<div class="container">
		<div class="row">
			<div class="col-lg-2 col-lg-offset-5">
				<hr class="marginbot-50">
			</div>
		</div>
        <div class="row">
            <div class="col-sm-3 col-md-3">
				<div class="wow fadeInLeft" data-wow-delay="0.2s">
                <div class="service-box">
					<div class="service-icon">
						<img src='<%= image_path("icons/improv.png") %>'> 
					</div>
					<div class="service-desc">
						<h5>Improvising</h5>
						<p>Courtney is hilarious both on and off stage. As a student cast member at <a href="http://www.brodytheater.com/" target="_blank">Brody Theater</a> in NW Portland she causes severe giggling every week.</p>
					</div>
                </div>
				</div>
            </div>
			<div class="col-sm-3 col-md-3">
				<div class="wow fadeInUp" data-wow-delay="0.2s">
                <div class="service-box">
					<div class="service-icon">
						<img src='<%= image_path("icons/climbing.png") %>'>
					</div>
					<div class="service-desc">
						<h5>Rock Climbing</h5>
						<p>Courtney enjoys indoor rock climbing and bouldering at <a href="http://portlandrockgym.com/" target="_blank">Portland Rock Gym</a>. She has yet to climb outdoors despite a <a href="https://scontent-sea1-1.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/12241294_10152845538899058_8427064305425055554_n.jpg?oh=96eb61e4fdc3629e69a5e7ac1ea635e6&oe=56B8A4F5" target="_blank">doctored photo</a> claiming otherwise.</p>
					</div>
                </div>
				</div>
            </div>
			<div class="col-sm-3 col-md-3">
				<div class="wow fadeInUp" data-wow-delay="0.2s">
                <div class="service-box">
					<div class="service-icon">
						<img src='<%= image_path("icons/hiking.png") %>'>
					</div>
					<div class="service-desc">
						<h5>Hiking</h5>
						<p>Courtney has hiked portions of the Appalachian Trail (AT) and Pacific Crest Trail (PCT) and plans to someday trek the famous <a href="http://www.incatrailperu.com/" target="_blank">Inca Trail</a>.</p>
					</div>
                </div>
				</div>
            </div>
			<div class="col-sm-3 col-md-3">
				<div class="wow fadeInRight" data-wow-delay="0.2s">
                <div class="service-box">
					<div class="service-icon">
						<img src='<%= image_path("icons/travel.png") %>'>
					</div>
					<div class="service-desc">
						<h5>Traveling</h5>
						<p>Courtney has visited many countries including South Africa, Italy, England and Greece. Next on the list: <a href="https://scontent.xx.fbcdn.net/hphotos-xlf1/v/t1.0-9/12239591_10152846267969058_630422407454909329_n.jpg?oh=761fa508a130419d4918e5ffe4a2ac06&oe=56E82DF7" target="_blank">Peru</a> and New Zealand.</p>
					</div>
                </div>
				</div>
            </div>
        </div>		
		</div>
	</section>
	<!-- /Section: services -->
	

	

	<!-- Section: contact -->
    <section id="contact" class="home-section text-center">
		<div class="heading-contact">
			<div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="wow bounceInDown" data-wow-delay="0.4s">
					<div class="section-heading">
					<h2>Sign the card</h2>
					<h3>Please share your silliest, most awesome stories, memories and well-wishes for Courtney to read on her birthday.</h3>
					<% if notice %><p id="notice">Thanks! <%= notice %></p><% end %>
					<i class="fa fa-2x fa-angle-down"></i>
					</div>
					</div>
				</div>
			</div>
			</div>
		</div>
		<div class="container">

		<div class="row">
			<div class="col-lg-2 col-lg-offset-5">
				<hr class="marginbot-50">
			</div>
		</div>
    <div class="row">
        <div class="col-lg-8">
            <div class="boxed-grey"> 
            	<%= render 'form' %>
            </div>
        </div>
		
		<div class="col-lg-4">
			<div class="widget-contact">
				<h5 style="margin:2px 0 10px">Mailing Address</h5>
				<p>Want to send a gag gift? Real card? Maybe something nifty from her Amazon wish list?
				<ul style="margin-top:-10px;margin-left:20px">
					<li><a href="http://www.amazon.com/dp/B00OS67TTM/ref=wl_it_dp_v_S_ttl?_encoding=UTF8&colid=32YKSH5HBOC6H&coliid=I1FZF4A0F9F650&psc=1" target="_blank">Northface backpack</a></li>
					<li><a href="https://www.amazon.com/dp/B0091PBSCE/ref=wl_it_dp_v_S_ttl?_encoding=UTF8&colid=32YKSH5HBOC6H&coliid=IZ34WEVETA2IE&psc=1" target="_blank">Bike helmet</a></li>
					<li> <a href="https://www.amazon.com/dp/B0039UU9U4/ref=wl_it_dp_v_nS_ttl?_encoding=UTF8&colid=32YKSH5HBOC6H&coliid=I22QPEH4FTNP3C&psc=1" target="_blank">Dutch oven</a></li>
				</ul>
				
				<address>
				  <strong>Courtney Rodi</strong><br>
				  2625 E Burnside St. #109<br>
				  Portland, OR 97214<br>
				</address>

	
				<address>
				  <strong>She's also on social networks</strong><br>
                       	<ul class="company-social">
                            <li class="social-facebook"><a href="https://www.facebook.com/crodi" target="_blank"><i class="fa fa-facebook"></i></a></li>
                            <li class="social-twitter"><a href="https://twitter.com/decatursun" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li class="social-instagram"><a href="https://www.instagram.com/decatursun76/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                            <li class="social-google"><a href="https://plus.google.com/100816275047146196334/" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                        </ul>	
				</address>					
			
			</div>	
		</div>
    </div>	

		</div>
	</section>
	<!-- /Section: contact -->
<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-lg-12">
					<div class="wow shake" data-wow-delay="0.4s">
					<div class="page-scroll marginbot-30">
						<a href="#intro" id="totop" class="btn btn-circle">
							<i class="fa fa-angle-double-up animated"></i>
						</a>
					</div>
					</div>
					<p>&copy; Copyright 2016 - JNP Designs. All rights reserved.</p>    
				</div>
			</div>	
		</div>
	</footer>


<%#= link_to 'Back', memories_path %>

app/views/memories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @memory.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @memory.email %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @memory.relationship %>
</p>

<p>
  <strong>Year met:</strong>
  <%= @memory.year_met %>
</p>

<p>
  <strong>Memory1:</strong>
  <%= @memory.memory1 %>
</p>

<p>
  <strong>Memory2:</strong>
  <%= @memory.memory2 %>
</p>

<p>
  <strong>Memory3:</strong>
  <%= @memory.memory3 %>
</p>

<%= link_to 'Edit', edit_memory_path(@memory) %> |
<%= link_to 'Back', memories_path %>